apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:wsuFQFD/L41t1Mnwl/SmFsqYi11AphZ8f4U3ZpzY1uvfsuUiVpyqD3LRvHbAKG6/u0wx3whsie2U4SD5478Av3QYd3vwDC27h6QTrjaV2RGD5/6zI4M/QB7OAY22cA0mHxB8xDSsuXXIXEaHz6VY4tpqOi6RxHoHZC9Kemi/g0jSsWRCBHp4dBhAgbhqaDbcm+++ssPTGVyiUnVcAqHWt4NeqoHOSl1i,iv:a462osl9GcS5vh35Btxi28HYfFYnwVQinfw9SlMTFds=,tag:vPK+xhVQLLQCM0UaO688OA==,type:str]
metadata:
    name: regcred
    namespace: chuchu
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16rspnzt6j2qxa2587t6umh9qykrqu2amrr0hx9xt2z7elyky3a3q4p5s7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UXFhQ05zSHp3VW5TaE5a
            a0ZOSXpvQVZEQnpNejQxTFpXaC9EL0ViZVI4CjVFWXJEdWhGK0JSZmZOaURoUFdI
            NTJldy9NV2RKMnVtUDlOQzJqZ09oMEEKLS0tIGFScktLOVFTZHJNWmRabnRYYitz
            V0FLMWlUNkV1NnQrQ3NQQmdaTUcwTDgK7GeLf3eNnTQ9Nzj5wdR7YS3Uo7/T1yjT
            o1Z3FzhXXu2uNc0b7+x7mCW0s/+IfLmXrgZXnrYxmqqeO1zdnpQc4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17gp6lqd6u457fjmqptyetnnhy8tx93hqt2juejlvrmujc54acces06dk4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdHlmbVlvR05UYkVZamVG
            Q0NvZVRCVWpHdnVIalBYY1NpRHYxOEtTNmdvCjRrRzljR2kyZEVKNjFYVlNaSXVF
            VW9PQTV2UnhCZ3hhNFJaZEw5VjdrRDgKLS0tIDdmbDJaUFVvNDdZR3RldVphK044
            Z01SOFBPOXNON1Zyb0NnWllHeHpGWUUK3P9I2c8copsiANzHZ9/6O9XLRlU8Lvth
            yFjEr94iJbW7pfiBqhpkJ+UxsDok05chTnKarNi4G3OkF/YvBQVPwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ssqw7t6pnmlpsrx4tkpucqtzj5vzksmtcwkgp3prp5rspyvyk5tq0u32cs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdWtmTFpDNVJPOGRtOUJB
            T0V4UlUvY1N4NzhHbmFNdHdLODlWbVpnQWwwCnF6ekNDWTFDR3Z1N1JuSW1BVnZ5
            RlM5cFhZN3BGZXl2VWJDNUVkVTRjRk0KLS0tIEVqWGRFMEpKVmVURlNPWGYwSkUw
            QmszWDRVNVZubDhYWjNZSTNHNU9Uc0EKAiBAyptx8L4ExRyHlRwNDEWP/wMY6ts7
            LtLuoIXPs975aeioBlw0oX8xGgnWygx9e1UsnJ4ms5uVdE3h7dN83A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age194m4ryt3tda6vmk7czxm362rumy9y9ngq5lsx50pdjzmfd0flg7q6ngszm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdHd2KzQ0Y0hRQlJQOVl6
            MlB5K3NsdjFwVzNJeXBnME4vY3NubEFIRlRBClhNUlZQRStrRzhVYkljTlpMZElp
            T0EzbTRheHNYcWlveEljdFJlVzFQQm8KLS0tIDMwT21VMlBHWkE2aWxUMDFISGJn
            VEp3SGhYUFFmWjJ3cGNNTlJVT3hjN3cKlQOV3lxD80IqGslpikCRiPOUxRSkKTcr
            WhsyChwGzYIa0VSLsG+uWQM8iZNRydNRTPrI2gFqV46nOLYXH0YJbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T09:50:09Z"
    mac: ENC[AES256_GCM,data:xOGJVikonEeLPsaGIOziM50bSj8gkaX+po+tMDZD1NPh+TvPQ3cmWT93BdnXgYxC6Y3J+kmwYGHrK4DY8133IbkCNApa3rXq1fdsHNEas8BEkt0OXnqnC3HWF18FHrQHTl29ZTS47szFrYU1rW4Dj1DrO110S2QKG55QKTNmy+c=,iv:5coi/C2r8h3fB35yBHXUAEEnH1qTFffnM3XXqBv0Sk0=,tag:TTvdrCegQy482oWYMdWqwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
